### ISSUE TITLE
sqlite3.OperationalError: no such table: feeds

### ISSUE THREAD

**Issue by Sakrecoer** [tassoman/mk-feed-bot#2]
I'm late to the party, but i pulled the latest change, and ever since i'm getting the following error:

```
Traceback (most recent call last):
  File "feed-bot.py", line 40, in <module>
    cu.execute("INSERT INTO feeds (url) VALUES (?)", (u,))
sqlite3.OperationalError: no such table: feeds
```

I think this table was previously called `news`... I will figure out how to rename it, but i'm putting this here in case someone else stumbles on the same error.

**Comment by tassoman** [comment]
At that time I was lazy/unable to write the SQL schema for `news` table.  
You can now [find it in the source code](https://github.com/tassoman/mk-feed-bot/blob/c6d4cd7d49dd87962393478a4d198acd0c80f714/jobs/fetch.py#L16-L27)
